### ISSUE TITLE
Sub record overflow for quest header

### ISSUE THREAD

**Issue by MoonbeamLure** [Mutagen-Modding/Mutagen#382]
It seems like there's still issues with subheader records. In Devious Devices - Expansion.esm from LoversLab, there's a quest ID that has a data size of 72870. When Mutagen reads this specific subrecord header it crashes (the errors from ESLify Everything below along with a nexus link). Thinking it had to do with a size limit I then removed just enough records to make the quest something like 65200 and it went through. 

[Pastebin.com](https://pastebin.com/7wTDxAhm)

https://www.nexusmods.com/skyrimspecialedition/mods/75248

edit: I guess I cut off the line numbers in the image, so I decided to just change it to a pastebin of the log instead.

**Comment by Michael-wigontherun** [comment]
@Noggog 

It's crashing on

foreach (var rec in mod.EnumerateMajorRecords()) 
{ 
     rec.IsCompressed = false; 
}

The foreach specifically.

**Comment by Michael-wigontherun** [comment]
@Noggog 
It might not be, I think he is on a earlier build then what I was looking at

**Comment by Noggog** [comment]
Yeah, overflow is a concept that only certain records are "marked to handle".   There's a card to make it more global that I haven't gotten to yet  #286 

Is this still a problem, or did upgrading version help?

If not, I'll need a bit more info:
- The subrecord type that's overflowing (i'll probably add this to the logs for the future)
- Link to the mod (not too familiar with finding things on LL).  You can hop on discord and PM it to me if you want

**Comment by Michael-wigontherun** [comment]
It was the foreach line. And its weird, I have it getting the record using the actual quest list and that doesn't crash.
var QuestsItemSet = mod.Quests.ToHashSet();
foreach (var sourceForm in QuestsItemSet)

**Comment by Noggog** [comment]
Do you have the stack trace?

**Comment by Michael-wigontherun** [comment]
This is from his log

System.AggregateException: One or more errors occurred. (Subrecord header export resulted in an overflow. Diff: 0x11C64)
 ---> RecordException  => zadxQuest (00CA01:Devious Devices - Expansion.esm<Quest>): Subrecord header export resulted in an overflow. Diff: 0x11C64 System.OverflowException: Subrecord header export resulted in an overflow. Diff: 0x11C64
   at Mutagen.Bethesda.Plugins.Binary.Translations.HeaderExport.Dispose()
   at Mutagen.Bethesda.Skyrim.QuestAdapterBinaryWriteTranslation.Write(MutagenWriter writer, IQuestAdapterGetter item, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.QuestBinaryWriteTranslation.WriteRecordTypes(IQuestGetter item, MutagenWriter writer, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.QuestBinaryWriteTranslation.Write(MutagenWriter writer, IQuestGetter item, TypedWriteParams translationParams)   at Mutagen.Bethesda.Skyrim.QuestBinaryWriteTranslation.Write(MutagenWriter writer, IQuestGetter item, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.QuestBinaryWriteTranslation.Write(MutagenWriter writer, Object item, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryWriteTranslation.<>c__2`1.<WriteRecordTypes>b__2_0(MutagenWriter r, T dictSubItem)
   at Mutagen.Bethesda.Translations.Binary.ListBinaryTranslation`3.Write(TWriter writer, IEnumerable`1 items, BinarySubWriteDelegate`2 transl)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryWriteTranslation.WriteRecordTypes[T](ISkyrimGroupGetter`1 item, MutagenWriter writer, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimGroupBinaryWriteTranslation.Write[T](MutagenWriter writer, ISkyrimGroupGetter`1 item, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryWriteTranslation.WriteRecordTypes(ISkyrimModGetter item, MutagenWriter writer, GroupMask importMask, TypedWriteParams translationParams)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryWriteTranslation.Write(MutagenWriter writer, ISkyrimModGetter item, ModKey modKey, GroupMask importMask, BinaryWriteParameters param)
   at Mutagen.Bethesda.Skyrim.SkyrimModBinaryTranslationMixIn.WriteToBinary(ISkyrimModGetter item, FilePath path, BinaryWriteParameters param, GroupMask importMask, IFileSystem fileSystem)
   at ESLifyEverything.PluginHandles.HandleMod.HandleSkyrimMod(String pluginName) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\PluginHandles\HandleMod.cs:line 71
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at ESLifyEverything.Program.ReadLoadOrder() in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ProgramSteps.cs:line 1246
   at ESLifyEverything.Program.Main(String[] args) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\Program.cs:line 148

**Comment by Noggog** [comment]
The reason you're not getting the crash in your foreach loop is that parsing is done lazily (https://github.com/Mutagen-Modding/Mutagen/wiki/Binary-Overlay).  So it's not until something like a write that it actually goes and parses all the fields -> triggering the error.

1)  Do you know what subrecord (VMAD, etc) that has the overflow offhand?
2)  If not, can you PM me the link to the mod so i can inspect it myself?

**Comment by MoonbeamLure** [comment]
> The reason you're not getting the crash in your foreach loop is that parsing is done lazily (https://github.com/Mutagen-Modding/Mutagen/wiki/Binary-Overlay). So it's not until something like a write that it actually goes and parses all the fields -> triggering the error.
> 
> 1. Do you know what subrecord (VMAD, etc) that has the overflow offhand?
> 2. If not, can you PM me the link to the mod so i can inspect it myself?

Yes, it's the record header I think under this: zadxQuest (00CA01:Devious Devices - Expansion.esm<Quest>). 

The data size of the record at 00CA01 is 72870 and the only way I've been able to get ESLify/Mutagen to finish reading the mod and fixing the data is by deleting enough of the properties to get the data size under 65535. Then, it would finish reading. I'm not sure if that's going to be helpful information at all.


Mod is located here: https://www.loverslab.com/files/file/5878-devious-devices-se/

Devious Devices is like 2GB and you can't really download just the Esm and scripts so I can take a picture of the subheader for you: https://imgur.com/JK3L0C1

Do let me know if you still would need to download it and I can get you the link they use for hosting it on Mega.nz. 

Thanks so much and again, do let me know if you need anything else!

edit: changed wording because I realized I didn't give you the correct description of the subrecord I believe is at issue.

**Comment by Noggog** [comment]
Cool, got what I needed!  Will be fixing for the next prerelease (sometime soon)
