### ISSUE TITLE
Print load order line and modname on failed plugins.txt parsing

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#435]
```
[1.4][Skyrim Special Edition] Load order location error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Mutagen.Bethesda.Plugins.ModKey.TryFromName(ReadOnlySpan`1 str, ModType type, ModKey& modKey, String& errorReason)
   at Mutagen.Bethesda.Plugins.ModKey.TryFromNameAndExtension(ReadOnlySpan`1 str, ModKey& modKey, String& errorReason)
   at Mutagen.Bethesda.Plugins.ModKey.TryFromNameAndExtension(ReadOnlySpan`1 str, ModKey& modKey)
   at Mutagen.Bethesda.Plugins.Order.LoadOrderListing.TryFromString(ReadOnlySpan`1 str, Boolean enabledMarkerProcessing, LoadOrderListing& listing)
   at Mutagen.Bethesda.Plugins.Order.LoadOrderListing.FromString(ReadOnlySpan`1 str, Boolean enabledMarkerProcessing)
   at Mutagen.Bethesda.Plugins.Order.DI.LoadOrderListingParser.FromString(ReadOnlySpan`1 str)
   at Mutagen.Bethesda.Plugins.Order.DI.PluginListingsParser.Parse(Stream stream)+MoveNext()
```

**Comment by studioph** [comment]
@Noggog you can assign this to me if you want to track it

**Comment by studioph** [comment]
Just so that I'm not being silly - the `IndexOutOfRangeException` doesn't appear to happen anymore - `LoadOrderListing` now throws an `InvalidDataException` if it can't parse the line. The exception includes the line contents, but not the line number in the file.

It was simple enough to add an additional test case for `PluginsListingParser` and update the `Parse` method to keep track of the current line and throw from there if `TryFromName` fails, but I feel like I should ask if this minor change to simply include the line number in the error message is still worthwhile? I realize the irony of asking that since I picked this issue in the first place not realizing the error message above is no longer what gets printed.

**Comment by studioph** [comment]
Basically comes down to:
```
InvalidDataException: Load order file had malformed line: Malformed.lolz
```
vs

```
InvalidDataException: Load order file had malformed entry at line 3: "Malformed.lolz"
```

**Comment by Noggog** [comment]
Bottom one looks nice.  Got the line number, and the actual line in quotes for clearer visual parsing
