### ISSUE TITLE
Parse Fallout 4 VR

### ISSUE THREAD

**Issue by Noggog** [Mutagen-Modding/Mutagen#488]
Create generated records for Fallout 4 VR

**Comment by Blazeyboyyy** [comment]
Hello @Noggog thank you for this. Unfortunately when I load Synthesis via my MO2 install for FO4VR I see an error message 

> Missing plugins.txt Load Order File

It still seems to be searching for the Fallout4\plugins.txt in my C:\Users\Me\AppData\Local\Fallout4\Plugins.txt folder.

Sorry if this is unrelated to the original issue, but could you help? Or is there anywhere else I can ask for help in resolving this?

**Comment by Noggog** [comment]
You were waiting for this:
https://github.com/Mutagen-Modding/Synthesis/releases/tag/0.27-pr001

Give that a shot, make a new profile for Fo4VR, add patchers there, and see how it goes

**Comment by Blazeyboyyy** [comment]
Thank you - sorry for noob questions, but is there a Synthesis.zip associated with this release? Not sure how else to install it.

Thanks again

**Comment by Noggog** [comment]
Sorry!  Publish event had issues.  Should be up now

**Comment by Blazeyboyyy** [comment]
No problem, thanks again.

I am trying to use one patcher called FOLIP - https://github.com/DoubleYouC/FOLIP but am getting this error:

System.IO.IOException: The process cannot access the file 'C:\Users\mypc\AppData\Local\Temp\Synthesis\bg4hkz2l.wsh\Workspace\Synthesis' because it is being used by another process.
   at Noggog.IFileSystemExt.DeleteEntireFolder(IDirectory system, DirectoryPath path, Boolean disableReadOnly, Boolean deleteFolderItself) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\IFileSystemExt.cs:line 69
   at Noggog.IFileSystemExt.DeleteEntireFolder(IDirectory system, DirectoryPath path, Boolean disableReadOnly, Boolean deleteFolderItself) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\IFileSystemExt.cs:line 52
   at Noggog.IO.DeleteEntireDirectory.DeleteEntireFolder(DirectoryPath dir, Boolean disableReadOnly, Boolean deleteFolderItself) in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\IO\DeleteEntireDirectory.cs:line 27
   at Synthesis.Bethesda.Execution.Running.Runner.ResetWorkingDirectory.Reset() in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ResetWorkingDirectory.cs:line 30
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 44
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Boolean utf8InEmbeddedStrings, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 47
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 209

**Comment by Noggog** [comment]
Hmm, getting off topic, so maybe should head to the discord
https://discord.gg/53KMEsW

But first guess is that maybe you have Antivirus going on?
https://github.com/Mutagen-Modding/Synthesis/discussions/203

**Comment by Vonklinkenhoffn** [comment]
@Blazeyboyyy Hi, I've stumbled across this thread looking for some answers myself. I play FO4 in VR. I've just installed Synthesis and I'm running it from MO2 without issues. However, I've naturally selected FO4VR in Synthesis, but in the list of patchers I can't find FOLIP. I need it to follow along with a tutorial. Did you ever get this to work? Do you mind telling me how you did it?

**Comment by Noggog** [comment]
@Vonklinkenhoffn made a card for this here
https://github.com/Mutagen-Modding/Synthesis/issues/449

In the meantime, you can add any patcher manually by pasting the patcher's github link into the `Input` pane of the git patcher, rather than looking at the patcher browser

**Comment by Vonklinkenhoffn** [comment]
@Noggog I had no idea that was a way to do it, thank you so much for this info! I'll get to it immediately.

**Comment by Vonklinkenhoffn** [comment]
@Noggog Worked like a charm, thanks for saving me!
